### ISSUE TITLE
After successfully running the requisite steps, I'm getting some issues related to SystemStyleObject

### ISSUE THREAD

**Issue by hawjefferson** [mParticle/mparticle-web-sample-apps#1]
Hi mParticle Team

After running the npm install and start command, I'm getting these errors showing up in the command line and also in the web browser console. Any ideas on how to fix this? Thank you

![image](https://user-images.githubusercontent.com/47293714/157788480-4b7b35d9-521a-433f-a32f-89363d371324.png)

Stack trace:

TypeScript error in /Users/jhaw/Downloads/mparticle-web-sample-apps-main/core-sdk-samples/higgs-shop-sample-app/src/components/NavigationMenu/NavigationMenu.tsx(116,9):
No overload matches this call.
  Overload 3 of 3, '(props: DefaultComponentProps<ExtendButtonBaseTypeMap<MenuItemTypeMap<{}, "li">>>): Element', gave the following error.
    Type 'SystemStyleObject<Theme> | CssVariableType | ((theme: Theme) => string | number | SystemStyleObject<Theme>)' is not assignable to type 'boolean | SystemStyleObject<Theme> | ((theme: Theme) => SystemStyleObject<Theme>)'.
  Overload 3 of 3, '(props: DefaultComponentProps<ExtendButtonBaseTypeMap<MenuItemTypeMap<{}, "li">>>): Element', gave the following error.
    Type 'SystemStyleObject<Theme> | CssVariableType | ((theme: Theme) => string | number | SystemStyleObject<Theme>)' is not assignable to type 'boolean | SystemStyleObject<Theme> | ((theme: Theme) => SystemStyleObject<Theme>)'.  TS2769

    114 |         </IconButton>,
    115 | 
  > 116 |         <MenuItem
        |         ^
    117 |             aria-label='Mobile Home Page'
    118 |             data-testid='mobile-nav-home-button'
    119 |             key='home'

**Comment by hawjefferson** [comment]
@alexs-mparticle i'm running on node v17.0.1 

jhaw-mbp16:higgs-shop-sample-app jhaw$ node -v
v17.0.1

**Comment by alexs-mparticle** [comment]
Thanks for letting me know. We developed this using node `v16.x`, so please try that just so we can rule out that there's something new in 17.x that's causing an issue. I'd recommend using NVM to manage your node versions locally if you can.

I'm going to set my dev environment to 17.0.1 to see if I can reproduce your issue.

**Comment by hawjefferson** [comment]
Hi Alex!

I've downgraded to v16.14.0 of node but I'm still getting some issues launching the app. Any ideas?

<img width="1754" alt="image" src="https://user-images.githubusercontent.com/47293714/158303296-e90d77ac-d2c4-49b6-ae93-90c141dddd0f.png">

**Comment by alexs-mparticle** [comment]
When you downgrade, delete your `node_modules` folder and `package-lock.json` then run `npm install` again. That _should_ work.

**Comment by hawjefferson** [comment]
Hi mParticle Team!

After pulling this version - https://github.com/mParticle/mparticle-web-sample-apps/pull/5 and setting my environment to the following version:

node -v
v16.14.0

npm -v
8.5.4

deleted package-lock.json

run npm install

then npm start, I was able to run the sample web application without any issues

Thank you
